import localFont from "next/font/local";
import "./globals.css";

const cheapsman = localFont({
  src: "./fonts/Cheapsman Free Regular.ttf",
  variable: "--font-cheaps",
});

export const metadata = {
  title: "Desgin hub static-site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cheapsman.variable} antialiased`}>{children}</body>
    </html>
  );
}
